# Generated by Django 4.1.4 on 2022-12-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_car_describtion_alter_car_model_alter_car_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name': 'my car'},
        ),
    ]
